services:
  ezxssdb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
    volumes:
      - "./ezxssdb:/var/lib/mysql"
  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USE_MAIL_ALERTS=${useMailAlerts}
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - ezxssdb
    env_file:
      - .env

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - LEGACY_DOMAIN=${LEGACY_DOMAIN:-localhost}
      - OOB_DOMAIN=${OOB_DOMAIN:-localhost}
      - NAMECHEAP_API_TOKEN=${NAMECHEAP_API_TOKEN:-123}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ezxss

volumes:
  ezxss_db:
  caddy_data:
  caddy_config: